services:
  db:
    image: postgres
    container_name: my_postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: blog_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # persistent storage
